<?xml version="1.0" encoding="utf-8"?><Database Name="ThuVien" Class="DBThuVienDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=COMPUTER-PC\SQLEXPRESS;Initial Catalog=ThuVien;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="ThuVienConnectionString" Provider="System.Data.SqlClient" />
</Database>